// "use client";

// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { UserProvider } from "../context/userContext";
// import { SessionProvider } from "next-auth/react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <SessionProvider>
//       <UserProvider>
//         <html lang="en">
//           <body className={`${geistSans.variable} ${geistMono.variable}`}>
//             {children}
//           </body>
//         </html>
//       </UserProvider>
//     </SessionProvider>
//   );
// }

// app/layout.js

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import ClientLayout from "./layout.client.js";

export default function RootLayout({ children }) {
  return <ClientLayout>{children}</ClientLayout>;
}
